[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
serde_json = { version = "1.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"